### ISSUE TITLE
Support enumeration literals

### ISSUE THREAD

**Issue by stelfrich** [scijava/scijava-expression-parser#4]
As predicted by @ctrueden in https://github.com/scijava/scijava-common/issues/199#issuecomment-153420274, parsing of enumeration values is currently not supported.

This is required for parameter parsing in scripts, for example:

```python
# @String(visibility=MESSAGE) text
```

**Comment by ctrueden** [comment]
It is tricky because right now, the parsing of attributes (inside the parentheses) is done in a way without any context, meaning that when parsing `visibility=MESSAGE` we have no knowledge of the fact that the `MESSAGE` token is supposed to be any particular type.

In SciJava Common, the `ParseService#parse(String)` method does not currently offer a way to inject that context, nor do I necessarily think we want to complicate the design of the parser in this way:

Consider a method `ParseService#parse(String arg, Map<String, Object> values)` which lets us pass known values such as `MESSAGE=ItemVisibility.MESSAGE`. The `ScriptInfo#parseAttrs(String)` method would then generate and pass in all enum values for all involved enum classes, where this information is happily known. Unfortunately, this scheme would not work if we had two different enumerations in play with overlapping keys, such as:
```
public enum MVerb { MASSAGE, MESSAGE, MUNGE, MANIPULATE }
...
# @MVerb(visibility=MESSAGE, value=MESSAGE) verb
```

What we _can_ do easily is to allow expressions like `visibility=MESSAGE` to resolve as "unresolved" when evaluating in a new non-strict mode. Then in the above example, the variable `visibility` will contain an object of type `Unresolved` with token value `"MESSAGE"`. And same for `value`. Then, downstream in SciJava Common, the script attribute assignment mechanism can take care of converting `Unresolved` objects to each needed type in a context-sensitive way.

I added such a non-strict mode in 720cdbe685eabc1e4835e89b1b0d97e6387de087, which resolves the issue on the SJEP side here.
